FROM alpine:latest

RUN apk add --no-cache ca-certificates tzdata

ARG TARGETARCH=amd64
ADD https://github.com/centrifugal/centrifugo/releases/download/v6.8.1/centrifugo_6.8.1_linux_${TARGETARCH}.tar.gz /tmp/

RUN tar xzf /tmp/centrifugo_6.8.1_linux_*.tar.gz -C /usr/local/bin/ centrifugo && \
    rm /tmp/centrifugo_*.tar.gz && \
    chmod +x /usr/local/bin/centrifugo

EXPOSE 8000

ENTRYPOINT ["centrifugo"]
CMD ["-c", "config.json"]
