// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: aureliomod/v1/content.proto

package aureliomodv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/soyAurelio/AurelioMod/proto/aureliomod/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ContentAnalysisServiceName is the fully-qualified name of the ContentAnalysisService service.
	ContentAnalysisServiceName = "aureliomod.v1.ContentAnalysisService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ContentAnalysisServiceAnalyzeProcedure is the fully-qualified name of the
	// ContentAnalysisService's Analyze RPC.
	ContentAnalysisServiceAnalyzeProcedure = "/aureliomod.v1.ContentAnalysisService/Analyze"
)

// ContentAnalysisServiceClient is a client for the aureliomod.v1.ContentAnalysisService service.
type ContentAnalysisServiceClient interface {
	// Analyze submits content for moderation analysis.
	// Returns immediately with a decision (block/allow) based on cache hits,
	// or a QUEUED status if WaveSpeed analysis is required.
	Analyze(context.Context, *connect.Request[v1.AnalyzeRequest]) (*connect.Response[v1.AnalyzeResponse], error)
}

// NewContentAnalysisServiceClient constructs a client for the aureliomod.v1.ContentAnalysisService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewContentAnalysisServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ContentAnalysisServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	contentAnalysisServiceMethods := v1.File_aureliomod_v1_content_proto.Services().ByName("ContentAnalysisService").Methods()
	return &contentAnalysisServiceClient{
		analyze: connect.NewClient[v1.AnalyzeRequest, v1.AnalyzeResponse](
			httpClient,
			baseURL+ContentAnalysisServiceAnalyzeProcedure,
			connect.WithSchema(contentAnalysisServiceMethods.ByName("Analyze")),
			connect.WithClientOptions(opts...),
		),
	}
}

// contentAnalysisServiceClient implements ContentAnalysisServiceClient.
type contentAnalysisServiceClient struct {
	analyze *connect.Client[v1.AnalyzeRequest, v1.AnalyzeResponse]
}

// Analyze calls aureliomod.v1.ContentAnalysisService.Analyze.
func (c *contentAnalysisServiceClient) Analyze(ctx context.Context, req *connect.Request[v1.AnalyzeRequest]) (*connect.Response[v1.AnalyzeResponse], error) {
	return c.analyze.CallUnary(ctx, req)
}

// ContentAnalysisServiceHandler is an implementation of the aureliomod.v1.ContentAnalysisService
// service.
type ContentAnalysisServiceHandler interface {
	// Analyze submits content for moderation analysis.
	// Returns immediately with a decision (block/allow) based on cache hits,
	// or a QUEUED status if WaveSpeed analysis is required.
	Analyze(context.Context, *connect.Request[v1.AnalyzeRequest]) (*connect.Response[v1.AnalyzeResponse], error)
}

// NewContentAnalysisServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewContentAnalysisServiceHandler(svc ContentAnalysisServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	contentAnalysisServiceMethods := v1.File_aureliomod_v1_content_proto.Services().ByName("ContentAnalysisService").Methods()
	contentAnalysisServiceAnalyzeHandler := connect.NewUnaryHandler(
		ContentAnalysisServiceAnalyzeProcedure,
		svc.Analyze,
		connect.WithSchema(contentAnalysisServiceMethods.ByName("Analyze")),
		connect.WithHandlerOptions(opts...),
	)
	return "/aureliomod.v1.ContentAnalysisService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ContentAnalysisServiceAnalyzeProcedure:
			contentAnalysisServiceAnalyzeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedContentAnalysisServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedContentAnalysisServiceHandler struct{}

func (UnimplementedContentAnalysisServiceHandler) Analyze(context.Context, *connect.Request[v1.AnalyzeRequest]) (*connect.Response[v1.AnalyzeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aureliomod.v1.ContentAnalysisService.Analyze is not implemented"))
}
