// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: aureliomod/v1/inference.proto

package aureliomodv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/soyAurelio/AurelioMod/proto/aureliomod/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// InferenceServiceName is the fully-qualified name of the InferenceService service.
	InferenceServiceName = "aureliomod.v1.InferenceService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// InferenceServiceClassifyProcedure is the fully-qualified name of the InferenceService's Classify
	// RPC.
	InferenceServiceClassifyProcedure = "/aureliomod.v1.InferenceService/Classify"
	// InferenceServiceHealthProcedure is the fully-qualified name of the InferenceService's Health RPC.
	InferenceServiceHealthProcedure = "/aureliomod.v1.InferenceService/Health"
)

// InferenceServiceClient is a client for the aureliomod.v1.InferenceService service.
type InferenceServiceClient interface {
	// Classify runs zero-shot classification on image(s) using SigLIP2.
	// Supports single images and batched video frames.
	Classify(context.Context, *connect.Request[v1.ClassifyRequest]) (*connect.Response[v1.ClassifyResponse], error)
	// Health returns model status and GPU information.
	Health(context.Context, *connect.Request[v1.HealthRequest]) (*connect.Response[v1.HealthResponse], error)
}

// NewInferenceServiceClient constructs a client for the aureliomod.v1.InferenceService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewInferenceServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) InferenceServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	inferenceServiceMethods := v1.File_aureliomod_v1_inference_proto.Services().ByName("InferenceService").Methods()
	return &inferenceServiceClient{
		classify: connect.NewClient[v1.ClassifyRequest, v1.ClassifyResponse](
			httpClient,
			baseURL+InferenceServiceClassifyProcedure,
			connect.WithSchema(inferenceServiceMethods.ByName("Classify")),
			connect.WithClientOptions(opts...),
		),
		health: connect.NewClient[v1.HealthRequest, v1.HealthResponse](
			httpClient,
			baseURL+InferenceServiceHealthProcedure,
			connect.WithSchema(inferenceServiceMethods.ByName("Health")),
			connect.WithClientOptions(opts...),
		),
	}
}

// inferenceServiceClient implements InferenceServiceClient.
type inferenceServiceClient struct {
	classify *connect.Client[v1.ClassifyRequest, v1.ClassifyResponse]
	health   *connect.Client[v1.HealthRequest, v1.HealthResponse]
}

// Classify calls aureliomod.v1.InferenceService.Classify.
func (c *inferenceServiceClient) Classify(ctx context.Context, req *connect.Request[v1.ClassifyRequest]) (*connect.Response[v1.ClassifyResponse], error) {
	return c.classify.CallUnary(ctx, req)
}

// Health calls aureliomod.v1.InferenceService.Health.
func (c *inferenceServiceClient) Health(ctx context.Context, req *connect.Request[v1.HealthRequest]) (*connect.Response[v1.HealthResponse], error) {
	return c.health.CallUnary(ctx, req)
}

// InferenceServiceHandler is an implementation of the aureliomod.v1.InferenceService service.
type InferenceServiceHandler interface {
	// Classify runs zero-shot classification on image(s) using SigLIP2.
	// Supports single images and batched video frames.
	Classify(context.Context, *connect.Request[v1.ClassifyRequest]) (*connect.Response[v1.ClassifyResponse], error)
	// Health returns model status and GPU information.
	Health(context.Context, *connect.Request[v1.HealthRequest]) (*connect.Response[v1.HealthResponse], error)
}

// NewInferenceServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewInferenceServiceHandler(svc InferenceServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	inferenceServiceMethods := v1.File_aureliomod_v1_inference_proto.Services().ByName("InferenceService").Methods()
	inferenceServiceClassifyHandler := connect.NewUnaryHandler(
		InferenceServiceClassifyProcedure,
		svc.Classify,
		connect.WithSchema(inferenceServiceMethods.ByName("Classify")),
		connect.WithHandlerOptions(opts...),
	)
	inferenceServiceHealthHandler := connect.NewUnaryHandler(
		InferenceServiceHealthProcedure,
		svc.Health,
		connect.WithSchema(inferenceServiceMethods.ByName("Health")),
		connect.WithHandlerOptions(opts...),
	)
	return "/aureliomod.v1.InferenceService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case InferenceServiceClassifyProcedure:
			inferenceServiceClassifyHandler.ServeHTTP(w, r)
		case InferenceServiceHealthProcedure:
			inferenceServiceHealthHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedInferenceServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedInferenceServiceHandler struct{}

func (UnimplementedInferenceServiceHandler) Classify(context.Context, *connect.Request[v1.ClassifyRequest]) (*connect.Response[v1.ClassifyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aureliomod.v1.InferenceService.Classify is not implemented"))
}

func (UnimplementedInferenceServiceHandler) Health(context.Context, *connect.Request[v1.HealthRequest]) (*connect.Response[v1.HealthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aureliomod.v1.InferenceService.Health is not implemented"))
}
