// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: aureliomod/v1/content.proto

package aureliomodv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Decision int32

const (
	Decision_DECISION_UNSPECIFIED Decision = 0
	Decision_DECISION_ALLOW       Decision = 1
	Decision_DECISION_BLOCK       Decision = 2
	Decision_DECISION_QUEUED      Decision = 3 // Pending WaveSpeed analysis
	Decision_DECISION_ERROR       Decision = 4 // Analysis failed; fallback to cached or block
)

// Enum value maps for Decision.
var (
	Decision_name = map[int32]string{
		0: "DECISION_UNSPECIFIED",
		1: "DECISION_ALLOW",
		2: "DECISION_BLOCK",
		3: "DECISION_QUEUED",
		4: "DECISION_ERROR",
	}
	Decision_value = map[string]int32{
		"DECISION_UNSPECIFIED": 0,
		"DECISION_ALLOW":       1,
		"DECISION_BLOCK":       2,
		"DECISION_QUEUED":      3,
		"DECISION_ERROR":       4,
	}
)

func (x Decision) Enum() *Decision {
	p := new(Decision)
	*p = x
	return p
}

func (x Decision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Decision) Descriptor() protoreflect.EnumDescriptor {
	return file_aureliomod_v1_content_proto_enumTypes[0].Descriptor()
}

func (Decision) Type() protoreflect.EnumType {
	return &file_aureliomod_v1_content_proto_enumTypes[0]
}

func (x Decision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Decision.Descriptor instead.
func (Decision) EnumDescriptor() ([]byte, []int) {
	return file_aureliomod_v1_content_proto_rawDescGZIP(), []int{0}
}

type ContentType int32

const (
	ContentType_CONTENT_TYPE_UNSPECIFIED  ContentType = 0
	ContentType_CONTENT_TYPE_IMAGE        ContentType = 1
	ContentType_CONTENT_TYPE_GIF          ContentType = 2
	ContentType_CONTENT_TYPE_VIDEO        ContentType = 3
	ContentType_CONTENT_TYPE_AUDIO        ContentType = 4
	ContentType_CONTENT_TYPE_EXTERNAL_URL ContentType = 5
	ContentType_CONTENT_TYPE_FINGERPRINT  ContentType = 6
)

// Enum value maps for ContentType.
var (
	ContentType_name = map[int32]string{
		0: "CONTENT_TYPE_UNSPECIFIED",
		1: "CONTENT_TYPE_IMAGE",
		2: "CONTENT_TYPE_GIF",
		3: "CONTENT_TYPE_VIDEO",
		4: "CONTENT_TYPE_AUDIO",
		5: "CONTENT_TYPE_EXTERNAL_URL",
		6: "CONTENT_TYPE_FINGERPRINT",
	}
	ContentType_value = map[string]int32{
		"CONTENT_TYPE_UNSPECIFIED":  0,
		"CONTENT_TYPE_IMAGE":        1,
		"CONTENT_TYPE_GIF":          2,
		"CONTENT_TYPE_VIDEO":        3,
		"CONTENT_TYPE_AUDIO":        4,
		"CONTENT_TYPE_EXTERNAL_URL": 5,
		"CONTENT_TYPE_FINGERPRINT":  6,
	}
)

func (x ContentType) Enum() *ContentType {
	p := new(ContentType)
	*p = x
	return p
}

func (x ContentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContentType) Descriptor() protoreflect.EnumDescriptor {
	return file_aureliomod_v1_content_proto_enumTypes[1].Descriptor()
}

func (ContentType) Type() protoreflect.EnumType {
	return &file_aureliomod_v1_content_proto_enumTypes[1]
}

func (x ContentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContentType.Descriptor instead.
func (ContentType) EnumDescriptor() ([]byte, []int) {
	return file_aureliomod_v1_content_proto_rawDescGZIP(), []int{1}
}

type SourcePlatform int32

const (
	SourcePlatform_SOURCE_PLATFORM_UNSPECIFIED SourcePlatform = 0
	SourcePlatform_SOURCE_PLATFORM_DISCORD     SourcePlatform = 1
	SourcePlatform_SOURCE_PLATFORM_TELEGRAM    SourcePlatform = 2
	SourcePlatform_SOURCE_PLATFORM_TWITCH      SourcePlatform = 3
	SourcePlatform_SOURCE_PLATFORM_TIKTOK      SourcePlatform = 4
	SourcePlatform_SOURCE_PLATFORM_KICK        SourcePlatform = 5
)

// Enum value maps for SourcePlatform.
var (
	SourcePlatform_name = map[int32]string{
		0: "SOURCE_PLATFORM_UNSPECIFIED",
		1: "SOURCE_PLATFORM_DISCORD",
		2: "SOURCE_PLATFORM_TELEGRAM",
		3: "SOURCE_PLATFORM_TWITCH",
		4: "SOURCE_PLATFORM_TIKTOK",
		5: "SOURCE_PLATFORM_KICK",
	}
	SourcePlatform_value = map[string]int32{
		"SOURCE_PLATFORM_UNSPECIFIED": 0,
		"SOURCE_PLATFORM_DISCORD":     1,
		"SOURCE_PLATFORM_TELEGRAM":    2,
		"SOURCE_PLATFORM_TWITCH":      3,
		"SOURCE_PLATFORM_TIKTOK":      4,
		"SOURCE_PLATFORM_KICK":        5,
	}
)

func (x SourcePlatform) Enum() *SourcePlatform {
	p := new(SourcePlatform)
	*p = x
	return p
}

func (x SourcePlatform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SourcePlatform) Descriptor() protoreflect.EnumDescriptor {
	return file_aureliomod_v1_content_proto_enumTypes[2].Descriptor()
}

func (SourcePlatform) Type() protoreflect.EnumType {
	return &file_aureliomod_v1_content_proto_enumTypes[2]
}

func (x SourcePlatform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SourcePlatform.Descriptor instead.
func (SourcePlatform) EnumDescriptor() ([]byte, []int) {
	return file_aureliomod_v1_content_proto_rawDescGZIP(), []int{2}
}

type CacheLevel int32

const (
	CacheLevel_CACHE_LEVEL_UNSPECIFIED CacheLevel = 0
	CacheLevel_CACHE_LEVEL_NONE        CacheLevel = 1 // Full analysis performed
	CacheLevel_CACHE_LEVEL_L1_BLAKE3   CacheLevel = 2 // Exact match (BLAKE3)
	CacheLevel_CACHE_LEVEL_L2_PHASH    CacheLevel = 3 // Perceptual match (pHash)
	CacheLevel_CACHE_LEVEL_L3_WEAVIATE CacheLevel = 4 // Semantic match (Weaviate)
)

// Enum value maps for CacheLevel.
var (
	CacheLevel_name = map[int32]string{
		0: "CACHE_LEVEL_UNSPECIFIED",
		1: "CACHE_LEVEL_NONE",
		2: "CACHE_LEVEL_L1_BLAKE3",
		3: "CACHE_LEVEL_L2_PHASH",
		4: "CACHE_LEVEL_L3_WEAVIATE",
	}
	CacheLevel_value = map[string]int32{
		"CACHE_LEVEL_UNSPECIFIED": 0,
		"CACHE_LEVEL_NONE":        1,
		"CACHE_LEVEL_L1_BLAKE3":   2,
		"CACHE_LEVEL_L2_PHASH":    3,
		"CACHE_LEVEL_L3_WEAVIATE": 4,
	}
)

func (x CacheLevel) Enum() *CacheLevel {
	p := new(CacheLevel)
	*p = x
	return p
}

func (x CacheLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CacheLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_aureliomod_v1_content_proto_enumTypes[3].Descriptor()
}

func (CacheLevel) Type() protoreflect.EnumType {
	return &file_aureliomod_v1_content_proto_enumTypes[3]
}

func (x CacheLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CacheLevel.Descriptor instead.
func (CacheLevel) EnumDescriptor() ([]byte, []int) {
	return file_aureliomod_v1_content_proto_rawDescGZIP(), []int{3}
}

type AnalyzeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// workspace_id identifies the customer workspace.
	WorkspaceId string `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	// content_id is a client-generated unique identifier for idempotency.
	ContentId string `protobuf:"bytes,2,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	// raw_bytes is the original content as received from the platform.
	RawBytes []byte `protobuf:"bytes,3,opt,name=raw_bytes,json=rawBytes,proto3" json:"raw_bytes,omitempty"`
	// content_type indicates the type of content being analyzed.
	ContentType ContentType `protobuf:"varint,4,opt,name=content_type,json=contentType,proto3,enum=aureliomod.v1.ContentType" json:"content_type,omitempty"`
	// source_platform indicates which platform the content came from.
	SourcePlatform SourcePlatform `protobuf:"varint,5,opt,name=source_platform,json=sourcePlatform,proto3,enum=aureliomod.v1.SourcePlatform" json:"source_platform,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AnalyzeRequest) Reset() {
	*x = AnalyzeRequest{}
	mi := &file_aureliomod_v1_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeRequest) ProtoMessage() {}

func (x *AnalyzeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aureliomod_v1_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeRequest) Descriptor() ([]byte, []int) {
	return file_aureliomod_v1_content_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *AnalyzeRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *AnalyzeRequest) GetRawBytes() []byte {
	if x != nil {
		return x.RawBytes
	}
	return nil
}

func (x *AnalyzeRequest) GetContentType() ContentType {
	if x != nil {
		return x.ContentType
	}
	return ContentType_CONTENT_TYPE_UNSPECIFIED
}

func (x *AnalyzeRequest) GetSourcePlatform() SourcePlatform {
	if x != nil {
		return x.SourcePlatform
	}
	return SourcePlatform_SOURCE_PLATFORM_UNSPECIFIED
}

type AnalyzeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// decision is the moderation decision.
	Decision Decision `protobuf:"varint,1,opt,name=decision,proto3,enum=aureliomod.v1.Decision" json:"decision,omitempty"`
	// block_reason is the human-readable explanation (required by DSA Art. 15).
	// Exposed in the dashboard as "statement of reasons".
	BlockReason string `protobuf:"bytes,2,opt,name=block_reason,json=blockReason,proto3" json:"block_reason,omitempty"`
	// confidence is the AI model confidence (0.0 to 1.0).
	Confidence float64 `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// category is the classification category (e.g., "violence_graphic").
	Category string `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	// content_hash is the BLAKE3 hash of the normalized content (L1 cache key).
	ContentHash string `protobuf:"bytes,5,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	// cache_level indicates which cache level produced the decision.
	CacheLevel CacheLevel `protobuf:"varint,6,opt,name=cache_level,json=cacheLevel,proto3,enum=aureliomod.v1.CacheLevel" json:"cache_level,omitempty"`
	// processing_ms is the total processing time in milliseconds.
	ProcessingMs int64 `protobuf:"varint,7,opt,name=processing_ms,json=processingMs,proto3" json:"processing_ms,omitempty"`
	// analyst_version is the WaveSpeed model version used (for audit).
	AnalystVersion string `protobuf:"bytes,8,opt,name=analyst_version,json=analystVersion,proto3" json:"analyst_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AnalyzeResponse) Reset() {
	*x = AnalyzeResponse{}
	mi := &file_aureliomod_v1_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeResponse) ProtoMessage() {}

func (x *AnalyzeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aureliomod_v1_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeResponse) Descriptor() ([]byte, []int) {
	return file_aureliomod_v1_content_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzeResponse) GetDecision() Decision {
	if x != nil {
		return x.Decision
	}
	return Decision_DECISION_UNSPECIFIED
}

func (x *AnalyzeResponse) GetBlockReason() string {
	if x != nil {
		return x.BlockReason
	}
	return ""
}

func (x *AnalyzeResponse) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *AnalyzeResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *AnalyzeResponse) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *AnalyzeResponse) GetCacheLevel() CacheLevel {
	if x != nil {
		return x.CacheLevel
	}
	return CacheLevel_CACHE_LEVEL_UNSPECIFIED
}

func (x *AnalyzeResponse) GetProcessingMs() int64 {
	if x != nil {
		return x.ProcessingMs
	}
	return 0
}

func (x *AnalyzeResponse) GetAnalystVersion() string {
	if x != nil {
		return x.AnalystVersion
	}
	return ""
}

var File_aureliomod_v1_content_proto protoreflect.FileDescriptor

const file_aureliomod_v1_content_proto_rawDesc = "" +
	"\n" +
	"\x1baureliomod/v1/content.proto\x12\raureliomod.v1\"\xf6\x01\n" +
	"\x0eAnalyzeRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x1d\n" +
	"\n" +
	"content_id\x18\x02 \x01(\tR\tcontentId\x12\x1b\n" +
	"\traw_bytes\x18\x03 \x01(\fR\brawBytes\x12=\n" +
	"\fcontent_type\x18\x04 \x01(\x0e2\x1a.aureliomod.v1.ContentTypeR\vcontentType\x12F\n" +
	"\x0fsource_platform\x18\x05 \x01(\x0e2\x1d.aureliomod.v1.SourcePlatformR\x0esourcePlatform\"\xd2\x02\n" +
	"\x0fAnalyzeResponse\x123\n" +
	"\bdecision\x18\x01 \x01(\x0e2\x17.aureliomod.v1.DecisionR\bdecision\x12!\n" +
	"\fblock_reason\x18\x02 \x01(\tR\vblockReason\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12!\n" +
	"\fcontent_hash\x18\x05 \x01(\tR\vcontentHash\x12:\n" +
	"\vcache_level\x18\x06 \x01(\x0e2\x19.aureliomod.v1.CacheLevelR\n" +
	"cacheLevel\x12#\n" +
	"\rprocessing_ms\x18\a \x01(\x03R\fprocessingMs\x12'\n" +
	"\x0fanalyst_version\x18\b \x01(\tR\x0eanalystVersion*u\n" +
	"\bDecision\x12\x18\n" +
	"\x14DECISION_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eDECISION_ALLOW\x10\x01\x12\x12\n" +
	"\x0eDECISION_BLOCK\x10\x02\x12\x13\n" +
	"\x0fDECISION_QUEUED\x10\x03\x12\x12\n" +
	"\x0eDECISION_ERROR\x10\x04*\xc6\x01\n" +
	"\vContentType\x12\x1c\n" +
	"\x18CONTENT_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CONTENT_TYPE_IMAGE\x10\x01\x12\x14\n" +
	"\x10CONTENT_TYPE_GIF\x10\x02\x12\x16\n" +
	"\x12CONTENT_TYPE_VIDEO\x10\x03\x12\x16\n" +
	"\x12CONTENT_TYPE_AUDIO\x10\x04\x12\x1d\n" +
	"\x19CONTENT_TYPE_EXTERNAL_URL\x10\x05\x12\x1c\n" +
	"\x18CONTENT_TYPE_FINGERPRINT\x10\x06*\xbe\x01\n" +
	"\x0eSourcePlatform\x12\x1f\n" +
	"\x1bSOURCE_PLATFORM_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17SOURCE_PLATFORM_DISCORD\x10\x01\x12\x1c\n" +
	"\x18SOURCE_PLATFORM_TELEGRAM\x10\x02\x12\x1a\n" +
	"\x16SOURCE_PLATFORM_TWITCH\x10\x03\x12\x1a\n" +
	"\x16SOURCE_PLATFORM_TIKTOK\x10\x04\x12\x18\n" +
	"\x14SOURCE_PLATFORM_KICK\x10\x05*\x91\x01\n" +
	"\n" +
	"CacheLevel\x12\x1b\n" +
	"\x17CACHE_LEVEL_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10CACHE_LEVEL_NONE\x10\x01\x12\x19\n" +
	"\x15CACHE_LEVEL_L1_BLAKE3\x10\x02\x12\x18\n" +
	"\x14CACHE_LEVEL_L2_PHASH\x10\x03\x12\x1b\n" +
	"\x17CACHE_LEVEL_L3_WEAVIATE\x10\x042b\n" +
	"\x16ContentAnalysisService\x12H\n" +
	"\aAnalyze\x12\x1d.aureliomod.v1.AnalyzeRequest\x1a\x1e.aureliomod.v1.AnalyzeResponseB\xb9\x01\n" +
	"\x11com.aureliomod.v1B\fContentProtoP\x01ZAgithub.com/soyAurelio/AurelioMod/proto/aureliomod/v1;aureliomodv1\xa2\x02\x03AXX\xaa\x02\rAureliomod.V1\xca\x02\rAureliomod\\V1\xe2\x02\x19Aureliomod\\V1\\GPBMetadata\xea\x02\x0eAureliomod::V1b\x06proto3"

var (
	file_aureliomod_v1_content_proto_rawDescOnce sync.Once
	file_aureliomod_v1_content_proto_rawDescData []byte
)

func file_aureliomod_v1_content_proto_rawDescGZIP() []byte {
	file_aureliomod_v1_content_proto_rawDescOnce.Do(func() {
		file_aureliomod_v1_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aureliomod_v1_content_proto_rawDesc), len(file_aureliomod_v1_content_proto_rawDesc)))
	})
	return file_aureliomod_v1_content_proto_rawDescData
}

var file_aureliomod_v1_content_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_aureliomod_v1_content_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_aureliomod_v1_content_proto_goTypes = []any{
	(Decision)(0),           // 0: aureliomod.v1.Decision
	(ContentType)(0),        // 1: aureliomod.v1.ContentType
	(SourcePlatform)(0),     // 2: aureliomod.v1.SourcePlatform
	(CacheLevel)(0),         // 3: aureliomod.v1.CacheLevel
	(*AnalyzeRequest)(nil),  // 4: aureliomod.v1.AnalyzeRequest
	(*AnalyzeResponse)(nil), // 5: aureliomod.v1.AnalyzeResponse
}
var file_aureliomod_v1_content_proto_depIdxs = []int32{
	1, // 0: aureliomod.v1.AnalyzeRequest.content_type:type_name -> aureliomod.v1.ContentType
	2, // 1: aureliomod.v1.AnalyzeRequest.source_platform:type_name -> aureliomod.v1.SourcePlatform
	0, // 2: aureliomod.v1.AnalyzeResponse.decision:type_name -> aureliomod.v1.Decision
	3, // 3: aureliomod.v1.AnalyzeResponse.cache_level:type_name -> aureliomod.v1.CacheLevel
	4, // 4: aureliomod.v1.ContentAnalysisService.Analyze:input_type -> aureliomod.v1.AnalyzeRequest
	5, // 5: aureliomod.v1.ContentAnalysisService.Analyze:output_type -> aureliomod.v1.AnalyzeResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_aureliomod_v1_content_proto_init() }
func file_aureliomod_v1_content_proto_init() {
	if File_aureliomod_v1_content_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aureliomod_v1_content_proto_rawDesc), len(file_aureliomod_v1_content_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aureliomod_v1_content_proto_goTypes,
		DependencyIndexes: file_aureliomod_v1_content_proto_depIdxs,
		EnumInfos:         file_aureliomod_v1_content_proto_enumTypes,
		MessageInfos:      file_aureliomod_v1_content_proto_msgTypes,
	}.Build()
	File_aureliomod_v1_content_proto = out.File
	file_aureliomod_v1_content_proto_goTypes = nil
	file_aureliomod_v1_content_proto_depIdxs = nil
}
