// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: aureliomod/v1/inference.proto

package aureliomodv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClassifyRequest submits content for SigLIP2 classification.
// The engine applies letterbox to 512×512 before sending.
type ClassifyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*ClassifyRequest_Image
	//	*ClassifyRequest_Video
	Content isClassifyRequest_Content `protobuf_oneof:"content"`
	// workspace_id carries the customer workspace for metrics and auditing.
	WorkspaceId string `protobuf:"bytes,3,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	// trace_id links this request to the engine's OpenTelemetry trace.
	TraceId string `protobuf:"bytes,4,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// workspace_tier controls video frame limits: free, pro, or enterprise.
	WorkspaceTier string `protobuf:"bytes,5,opt,name=workspace_tier,json=workspaceTier,proto3" json:"workspace_tier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassifyRequest) Reset() {
	*x = ClassifyRequest{}
	mi := &file_aureliomod_v1_inference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyRequest) ProtoMessage() {}

func (x *ClassifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aureliomod_v1_inference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyRequest.ProtoReflect.Descriptor instead.
func (*ClassifyRequest) Descriptor() ([]byte, []int) {
	return file_aureliomod_v1_inference_proto_rawDescGZIP(), []int{0}
}

func (x *ClassifyRequest) GetContent() isClassifyRequest_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ClassifyRequest) GetImage() *ImageInput {
	if x != nil {
		if x, ok := x.Content.(*ClassifyRequest_Image); ok {
			return x.Image
		}
	}
	return nil
}

func (x *ClassifyRequest) GetVideo() *VideoInput {
	if x != nil {
		if x, ok := x.Content.(*ClassifyRequest_Video); ok {
			return x.Video
		}
	}
	return nil
}

func (x *ClassifyRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *ClassifyRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ClassifyRequest) GetWorkspaceTier() string {
	if x != nil {
		return x.WorkspaceTier
	}
	return ""
}

type isClassifyRequest_Content interface {
	isClassifyRequest_Content()
}

type ClassifyRequest_Image struct {
	Image *ImageInput `protobuf:"bytes,1,opt,name=image,proto3,oneof"`
}

type ClassifyRequest_Video struct {
	Video *VideoInput `protobuf:"bytes,2,opt,name=video,proto3,oneof"`
}

func (*ClassifyRequest_Image) isClassifyRequest_Content() {}

func (*ClassifyRequest_Video) isClassifyRequest_Content() {}

// ImageInput carries a single JPEG already letterboxed to 512×512.
type ImageInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// jpeg_data is the image with letterbox padding applied by the engine.
	JpegData []byte `protobuf:"bytes,1,opt,name=jpeg_data,json=jpegData,proto3" json:"jpeg_data,omitempty"`
	// original dimensions for metrics and audit logging.
	OriginalWidth  int32 `protobuf:"varint,2,opt,name=original_width,json=originalWidth,proto3" json:"original_width,omitempty"`
	OriginalHeight int32 `protobuf:"varint,3,opt,name=original_height,json=originalHeight,proto3" json:"original_height,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ImageInput) Reset() {
	*x = ImageInput{}
	mi := &file_aureliomod_v1_inference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageInput) ProtoMessage() {}

func (x *ImageInput) ProtoReflect() protoreflect.Message {
	mi := &file_aureliomod_v1_inference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageInput.ProtoReflect.Descriptor instead.
func (*ImageInput) Descriptor() ([]byte, []int) {
	return file_aureliomod_v1_inference_proto_rawDescGZIP(), []int{1}
}

func (x *ImageInput) GetJpegData() []byte {
	if x != nil {
		return x.JpegData
	}
	return nil
}

func (x *ImageInput) GetOriginalWidth() int32 {
	if x != nil {
		return x.OriginalWidth
	}
	return 0
}

func (x *ImageInput) GetOriginalHeight() int32 {
	if x != nil {
		return x.OriginalHeight
	}
	return 0
}

// VideoInput carries individual frames extracted by the engine.
// Frames are sent in a single batch for parallel GPU inference.
type VideoInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// frames are JPEGs with letterbox to 512×512. Max frames per tier.
	Frames [][]byte `protobuf:"bytes,1,rep,name=frames,proto3" json:"frames,omitempty"`
	// aggregation strategy: "max" (default) takes the highest score per category
	// across all frames. "weighted" gives more weight to middle frames.
	Aggregation string `protobuf:"bytes,2,opt,name=aggregation,proto3" json:"aggregation,omitempty"`
	// duration_sec is the total video duration for metrics.
	DurationSec float32 `protobuf:"fixed32,3,opt,name=duration_sec,json=durationSec,proto3" json:"duration_sec,omitempty"`
	// extraction_fps is the frame extraction rate (1fps or 2fps enterprise).
	ExtractionFps float32 `protobuf:"fixed32,4,opt,name=extraction_fps,json=extractionFps,proto3" json:"extraction_fps,omitempty"`
	// is_partial_scan is true when a trusted-domain video exceeds tier limits
	// and only the first N seconds were scanned.
	IsPartialScan bool `protobuf:"varint,5,opt,name=is_partial_scan,json=isPartialScan,proto3" json:"is_partial_scan,omitempty"`
	// scanned_seconds is the actual duration scanned in this batch.
	ScannedSeconds float32 `protobuf:"fixed32,6,opt,name=scanned_seconds,json=scannedSeconds,proto3" json:"scanned_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VideoInput) Reset() {
	*x = VideoInput{}
	mi := &file_aureliomod_v1_inference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoInput) ProtoMessage() {}

func (x *VideoInput) ProtoReflect() protoreflect.Message {
	mi := &file_aureliomod_v1_inference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoInput.ProtoReflect.Descriptor instead.
func (*VideoInput) Descriptor() ([]byte, []int) {
	return file_aureliomod_v1_inference_proto_rawDescGZIP(), []int{2}
}

func (x *VideoInput) GetFrames() [][]byte {
	if x != nil {
		return x.Frames
	}
	return nil
}

func (x *VideoInput) GetAggregation() string {
	if x != nil {
		return x.Aggregation
	}
	return ""
}

func (x *VideoInput) GetDurationSec() float32 {
	if x != nil {
		return x.DurationSec
	}
	return 0
}

func (x *VideoInput) GetExtractionFps() float32 {
	if x != nil {
		return x.ExtractionFps
	}
	return 0
}

func (x *VideoInput) GetIsPartialScan() bool {
	if x != nil {
		return x.IsPartialScan
	}
	return false
}

func (x *VideoInput) GetScannedSeconds() float32 {
	if x != nil {
		return x.ScannedSeconds
	}
	return 0
}

// ClassifyResponse contains zero-shot classification results.
type ClassifyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// scores maps category name to sigmoid probability (0.0 to 1.0).
	// Categories: sexual, violence, hate, harassment, self_harm, sexual_minors.
	Scores map[string]float32 `protobuf:"bytes,1,rep,name=scores,proto3" json:"scores,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	// top_category is the category with the highest score.
	TopCategory string `protobuf:"bytes,2,opt,name=top_category,json=topCategory,proto3" json:"top_category,omitempty"`
	// confidence is the sigmoid score of the top category.
	Confidence float32 `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// triggered lists categories where score exceeds the category threshold.
	Triggered []string `protobuf:"bytes,4,rep,name=triggered,proto3" json:"triggered,omitempty"`
	// inference_ms is GPU inference time (Triton batch processing).
	InferenceMs int64 `protobuf:"varint,5,opt,name=inference_ms,json=inferenceMs,proto3" json:"inference_ms,omitempty"`
	// batch_size is the number of images processed in this batch.
	BatchSize int32 `protobuf:"varint,6,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	// model_version identifies the SigLIP2 model: "siglip2-512-1.0.0".
	ModelVersion string `protobuf:"bytes,7,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	// is_partial_scan echoes the input flag for the engine's decision logic.
	IsPartialScan bool `protobuf:"varint,8,opt,name=is_partial_scan,json=isPartialScan,proto3" json:"is_partial_scan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassifyResponse) Reset() {
	*x = ClassifyResponse{}
	mi := &file_aureliomod_v1_inference_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyResponse) ProtoMessage() {}

func (x *ClassifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aureliomod_v1_inference_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyResponse.ProtoReflect.Descriptor instead.
func (*ClassifyResponse) Descriptor() ([]byte, []int) {
	return file_aureliomod_v1_inference_proto_rawDescGZIP(), []int{3}
}

func (x *ClassifyResponse) GetScores() map[string]float32 {
	if x != nil {
		return x.Scores
	}
	return nil
}

func (x *ClassifyResponse) GetTopCategory() string {
	if x != nil {
		return x.TopCategory
	}
	return ""
}

func (x *ClassifyResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ClassifyResponse) GetTriggered() []string {
	if x != nil {
		return x.Triggered
	}
	return nil
}

func (x *ClassifyResponse) GetInferenceMs() int64 {
	if x != nil {
		return x.InferenceMs
	}
	return 0
}

func (x *ClassifyResponse) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *ClassifyResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *ClassifyResponse) GetIsPartialScan() bool {
	if x != nil {
		return x.IsPartialScan
	}
	return false
}

// HealthRequest checks readiness of the Inference Service.
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_aureliomod_v1_inference_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aureliomod_v1_inference_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_aureliomod_v1_inference_proto_rawDescGZIP(), []int{4}
}

// HealthResponse reports model and GPU status.
type HealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ready indicates the model is loaded and accepting requests.
	Ready bool `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	// model_version is the loaded SigLIP2 model version.
	ModelVersion string `protobuf:"bytes,2,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	// loaded_at_unix is the Unix timestamp when the model was loaded.
	LoadedAtUnix int64 `protobuf:"varint,3,opt,name=loaded_at_unix,json=loadedAtUnix,proto3" json:"loaded_at_unix,omitempty"`
	// gpu contains GPU hardware information.
	Gpu           *GpuInfo `protobuf:"bytes,4,opt,name=gpu,proto3" json:"gpu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_aureliomod_v1_inference_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aureliomod_v1_inference_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_aureliomod_v1_inference_proto_rawDescGZIP(), []int{5}
}

func (x *HealthResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *HealthResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *HealthResponse) GetLoadedAtUnix() int64 {
	if x != nil {
		return x.LoadedAtUnix
	}
	return 0
}

func (x *HealthResponse) GetGpu() *GpuInfo {
	if x != nil {
		return x.Gpu
	}
	return nil
}

// GpuInfo reports GPU hardware status via NVML.
type GpuInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the GPU model name (e.g., "NVIDIA RTX 5080").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// total_memory_mb is total VRAM in megabytes.
	TotalMemoryMb int64 `protobuf:"varint,2,opt,name=total_memory_mb,json=totalMemoryMb,proto3" json:"total_memory_mb,omitempty"`
	// free_memory_mb is available VRAM in megabytes.
	FreeMemoryMb int64 `protobuf:"varint,3,opt,name=free_memory_mb,json=freeMemoryMb,proto3" json:"free_memory_mb,omitempty"`
	// utilization_percent is current GPU utilization (0-100).
	UtilizationPercent float32 `protobuf:"fixed32,4,opt,name=utilization_percent,json=utilizationPercent,proto3" json:"utilization_percent,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GpuInfo) Reset() {
	*x = GpuInfo{}
	mi := &file_aureliomod_v1_inference_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GpuInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GpuInfo) ProtoMessage() {}

func (x *GpuInfo) ProtoReflect() protoreflect.Message {
	mi := &file_aureliomod_v1_inference_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GpuInfo.ProtoReflect.Descriptor instead.
func (*GpuInfo) Descriptor() ([]byte, []int) {
	return file_aureliomod_v1_inference_proto_rawDescGZIP(), []int{6}
}

func (x *GpuInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GpuInfo) GetTotalMemoryMb() int64 {
	if x != nil {
		return x.TotalMemoryMb
	}
	return 0
}

func (x *GpuInfo) GetFreeMemoryMb() int64 {
	if x != nil {
		return x.FreeMemoryMb
	}
	return 0
}

func (x *GpuInfo) GetUtilizationPercent() float32 {
	if x != nil {
		return x.UtilizationPercent
	}
	return 0
}

var File_aureliomod_v1_inference_proto protoreflect.FileDescriptor

const file_aureliomod_v1_inference_proto_rawDesc = "" +
	"\n" +
	"\x1daureliomod/v1/inference.proto\x12\raureliomod.v1\"\xe7\x01\n" +
	"\x0fClassifyRequest\x121\n" +
	"\x05image\x18\x01 \x01(\v2\x19.aureliomod.v1.ImageInputH\x00R\x05image\x121\n" +
	"\x05video\x18\x02 \x01(\v2\x19.aureliomod.v1.VideoInputH\x00R\x05video\x12!\n" +
	"\fworkspace_id\x18\x03 \x01(\tR\vworkspaceId\x12\x19\n" +
	"\btrace_id\x18\x04 \x01(\tR\atraceId\x12%\n" +
	"\x0eworkspace_tier\x18\x05 \x01(\tR\rworkspaceTierB\t\n" +
	"\acontent\"y\n" +
	"\n" +
	"ImageInput\x12\x1b\n" +
	"\tjpeg_data\x18\x01 \x01(\fR\bjpegData\x12%\n" +
	"\x0eoriginal_width\x18\x02 \x01(\x05R\roriginalWidth\x12'\n" +
	"\x0foriginal_height\x18\x03 \x01(\x05R\x0eoriginalHeight\"\xe1\x01\n" +
	"\n" +
	"VideoInput\x12\x16\n" +
	"\x06frames\x18\x01 \x03(\fR\x06frames\x12 \n" +
	"\vaggregation\x18\x02 \x01(\tR\vaggregation\x12!\n" +
	"\fduration_sec\x18\x03 \x01(\x02R\vdurationSec\x12%\n" +
	"\x0eextraction_fps\x18\x04 \x01(\x02R\rextractionFps\x12&\n" +
	"\x0fis_partial_scan\x18\x05 \x01(\bR\risPartialScan\x12'\n" +
	"\x0fscanned_seconds\x18\x06 \x01(\x02R\x0escannedSeconds\"\x82\x03\n" +
	"\x10ClassifyResponse\x12C\n" +
	"\x06scores\x18\x01 \x03(\v2+.aureliomod.v1.ClassifyResponse.ScoresEntryR\x06scores\x12!\n" +
	"\ftop_category\x18\x02 \x01(\tR\vtopCategory\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\x12\x1c\n" +
	"\ttriggered\x18\x04 \x03(\tR\ttriggered\x12!\n" +
	"\finference_ms\x18\x05 \x01(\x03R\vinferenceMs\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x06 \x01(\x05R\tbatchSize\x12#\n" +
	"\rmodel_version\x18\a \x01(\tR\fmodelVersion\x12&\n" +
	"\x0fis_partial_scan\x18\b \x01(\bR\risPartialScan\x1a9\n" +
	"\vScoresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\"\x0f\n" +
	"\rHealthRequest\"\x9b\x01\n" +
	"\x0eHealthResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12#\n" +
	"\rmodel_version\x18\x02 \x01(\tR\fmodelVersion\x12$\n" +
	"\x0eloaded_at_unix\x18\x03 \x01(\x03R\floadedAtUnix\x12(\n" +
	"\x03gpu\x18\x04 \x01(\v2\x16.aureliomod.v1.GpuInfoR\x03gpu\"\x9c\x01\n" +
	"\aGpuInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12&\n" +
	"\x0ftotal_memory_mb\x18\x02 \x01(\x03R\rtotalMemoryMb\x12$\n" +
	"\x0efree_memory_mb\x18\x03 \x01(\x03R\ffreeMemoryMb\x12/\n" +
	"\x13utilization_percent\x18\x04 \x01(\x02R\x12utilizationPercent2\xa6\x01\n" +
	"\x10InferenceService\x12K\n" +
	"\bClassify\x12\x1e.aureliomod.v1.ClassifyRequest\x1a\x1f.aureliomod.v1.ClassifyResponse\x12E\n" +
	"\x06Health\x12\x1c.aureliomod.v1.HealthRequest\x1a\x1d.aureliomod.v1.HealthResponseB\xbb\x01\n" +
	"\x11com.aureliomod.v1B\x0eInferenceProtoP\x01ZAgithub.com/soyAurelio/AurelioMod/proto/aureliomod/v1;aureliomodv1\xa2\x02\x03AXX\xaa\x02\rAureliomod.V1\xca\x02\rAureliomod\\V1\xe2\x02\x19Aureliomod\\V1\\GPBMetadata\xea\x02\x0eAureliomod::V1b\x06proto3"

var (
	file_aureliomod_v1_inference_proto_rawDescOnce sync.Once
	file_aureliomod_v1_inference_proto_rawDescData []byte
)

func file_aureliomod_v1_inference_proto_rawDescGZIP() []byte {
	file_aureliomod_v1_inference_proto_rawDescOnce.Do(func() {
		file_aureliomod_v1_inference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aureliomod_v1_inference_proto_rawDesc), len(file_aureliomod_v1_inference_proto_rawDesc)))
	})
	return file_aureliomod_v1_inference_proto_rawDescData
}

var file_aureliomod_v1_inference_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_aureliomod_v1_inference_proto_goTypes = []any{
	(*ClassifyRequest)(nil),  // 0: aureliomod.v1.ClassifyRequest
	(*ImageInput)(nil),       // 1: aureliomod.v1.ImageInput
	(*VideoInput)(nil),       // 2: aureliomod.v1.VideoInput
	(*ClassifyResponse)(nil), // 3: aureliomod.v1.ClassifyResponse
	(*HealthRequest)(nil),    // 4: aureliomod.v1.HealthRequest
	(*HealthResponse)(nil),   // 5: aureliomod.v1.HealthResponse
	(*GpuInfo)(nil),          // 6: aureliomod.v1.GpuInfo
	nil,                      // 7: aureliomod.v1.ClassifyResponse.ScoresEntry
}
var file_aureliomod_v1_inference_proto_depIdxs = []int32{
	1, // 0: aureliomod.v1.ClassifyRequest.image:type_name -> aureliomod.v1.ImageInput
	2, // 1: aureliomod.v1.ClassifyRequest.video:type_name -> aureliomod.v1.VideoInput
	7, // 2: aureliomod.v1.ClassifyResponse.scores:type_name -> aureliomod.v1.ClassifyResponse.ScoresEntry
	6, // 3: aureliomod.v1.HealthResponse.gpu:type_name -> aureliomod.v1.GpuInfo
	0, // 4: aureliomod.v1.InferenceService.Classify:input_type -> aureliomod.v1.ClassifyRequest
	4, // 5: aureliomod.v1.InferenceService.Health:input_type -> aureliomod.v1.HealthRequest
	3, // 6: aureliomod.v1.InferenceService.Classify:output_type -> aureliomod.v1.ClassifyResponse
	5, // 7: aureliomod.v1.InferenceService.Health:output_type -> aureliomod.v1.HealthResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_aureliomod_v1_inference_proto_init() }
func file_aureliomod_v1_inference_proto_init() {
	if File_aureliomod_v1_inference_proto != nil {
		return
	}
	file_aureliomod_v1_inference_proto_msgTypes[0].OneofWrappers = []any{
		(*ClassifyRequest_Image)(nil),
		(*ClassifyRequest_Video)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aureliomod_v1_inference_proto_rawDesc), len(file_aureliomod_v1_inference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aureliomod_v1_inference_proto_goTypes,
		DependencyIndexes: file_aureliomod_v1_inference_proto_depIdxs,
		MessageInfos:      file_aureliomod_v1_inference_proto_msgTypes,
	}.Build()
	File_aureliomod_v1_inference_proto = out.File
	file_aureliomod_v1_inference_proto_goTypes = nil
	file_aureliomod_v1_inference_proto_depIdxs = nil
}
